//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int id_admin { get; set; }
        public string email { get; set; }
        public string pword { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
