//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria_libro
    {
        public Categoria_libro()
        {
            this.Libroes = new HashSet<Libro>();
        }
    
        public int id_categoria_libro { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<Libro> Libroes { get; set; }
    }
}
