//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestamoLibro
    {
        public int id_prestamo { get; set; }
        public int id_libro { get; set; }
        public int cantidad { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Prestamo Prestamo { get; set; }
    }
}
