//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public Prestamo()
        {
            this.PrestamoLibroes = new HashSet<PrestamoLibro>();
        }
    
        public int id_prestamo { get; set; }
        public Nullable<int> id_tipo_prestamo { get; set; }
        public Nullable<System.DateTime> fecha_prestamo { get; set; }
        public Nullable<System.DateTime> fecha_devolucion { get; set; }
        public int id_personal { get; set; }
        public int id_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual ICollection<PrestamoLibro> PrestamoLibroes { get; set; }
        public virtual Tipo_De_Prestamo Tipo_De_Prestamo { get; set; }
    }
}
