//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_De_Prestamo
    {
        public Tipo_De_Prestamo()
        {
            this.Prestamoes = new HashSet<Prestamo>();
        }
    
        public int id_tipo_prestamo { get; set; }
        public string tipo_prestamo { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual ICollection<Prestamo> Prestamoes { get; set; }
    }
}
