//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.VentaLibroes = new HashSet<VentaLibro>();
        }
    
        public int id_venta { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
        public int id_personal { get; set; }
        public int id_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual ICollection<VentaLibro> VentaLibroes { get; set; }
    }
}
